version: '3.4'

services:
  db:
    image: rest-with-asp-net-udemy-db
    command: mysql --defaul-authemtication-plugin=mysql_native_password
    restart: always
    build:
      context:
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_apinet
  rest-with-asp-net-udemy:
    image: rest-with-asp-net-udemy
    build:
      context: .
      dockerfile: RestWithASPNETUdemy/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPENETCORE_ENVIRONMENT: Production